name: final_ecommerce

description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.7
  shared_preferences: ^2.2.2
  badges: ^3.1.1
  image_picker: ^1.0.4
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_svg: ^2.0.7
  

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png" 